---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-telegraf-1404
    image: ubuntu:14.04
  - name: ansible-role-telegraf-1604
    image: solita/ubuntu-systemd:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
